### ISSUE TITLE
can't remove attributes with false values

### ISSUE THREAD

**Issue by justmeandtaken** [crysalead-js/dom-layer#10]
@jails I'm now studying Deko, and I see there is no option for removing attributes if there is a false value? Have a look here: https://github.com/segmentio/deku/blob/master/lib/virtual.js#L183-L191

And how are boolean attributes set?

**Comment by jails** [comment]
Attributes are all string values by definition. So assuming that `undefined`, `false`, `null` are not valid attributes is a way to go.

**Comment by justmeandtaken** [comment]
@jails I just mentioned it because after the DOM Living specs, the attribute will be removed if false or null. In dom-layer it will not be set, or?
CitoJS handle both of this, and also boolean attributes. What is your plan about boolean attributes?

**Comment by jails** [comment]
I don't understand what you mean. Attributes are only string values and are updated according a "diffing strategy". During the patching process the `attrs` of the previous virtual nodes are compared to their respective new `attrs`. So if for a specific attribute perviously setted (i.e was `!= null`) the new value is either `false`, `null` or `undefinerd`, the attribute is just removed: https://github.com/crysalead-js/dom-layer/blob/master/node/setter/apply-attrs.js#L13-15

So I've no plan to deal with boolean attributes. And the way to remove an attribute of a DOM element, just set its value to `== null` in its new node `attrs` definition.
