### ISSUE TITLE
issues with setting values and attributes

### ISSUE THREAD

**Issue by justmeandtaken** [crysalead-js/dom-layer#11]
@jails Seems like there are issues setting values, such as checkbox, radio and select. I also had trouble setting a value on a textarea.

This seems to cause a problem:
 https://github.com/crysalead-js/dom-layer/blob/master/dist/dom-layer.js#L658

Shouldn't this be set as an attribute? A test case broke, and as you see here, the function who call this is:
https://github.com/crysalead-js/dom-layer/blob/master/dist/dom-layer.js#L658

Meaning you are setting attributes, but ending up setting a property??

**Comment by justmeandtaken** [comment]
@jails See this two test cases: https://github.com/crysalead-js/dom-layer/blob/master/spec/node/setter/apply-attrs-spec.js#L96-L138

Both of them are about properties, but the main function calling them are handle attributes.

Btw, AngularJS has a similar approach to your 'value':
https://github.com/angular/angular.js/blob/master/src/jqLite.js#L653-L668
but they have a different approach when it comes to checkboxes etc. : https://github.com/angular/angular.js/blob/master/src/jqLite.js#L600-L630
Same with REACT.

**Comment by justmeandtaken** [comment]
And how are you dealing with **selectedIndex**?

**Comment by justmeandtaken** [comment]
@jails How are you going to set **<select multiple>** ??

**Comment by jails** [comment]
Indeed there was an issue on rendering, good catch :+1: !
You can set the value of an input by simply setting its value attribute but if you want to use `selectedIndex`, it must be used as a property not an attribute (indeed pretty much all should be setted as an attribute except some properties related to input elements).
https://jsfiddle.net/j3Ls2pdj/

**Comment by justmeandtaken** [comment]
@jails but how are you going to set a select multiple?

**Comment by jails** [comment]
Check the fiddle ;-)

**Comment by justmeandtaken** [comment]
Ah. I just did. Just now I dealing with an issue with your latest select changes

**Comment by justmeandtaken** [comment]
@jails Have you tried to set a value on a textarea? Maybe I do something wrong, but for me it seems that your **default** in the *switch* are fucking it up.

And if you checking closely, you will see that some "types" are returned in upperCase, e.g. OPTIONS, but some others are returning in lowerCase

**Comment by jails** [comment]
Not sure to get what you mean: https://jsfiddle.net/La4an8j2/
Btw it would be easier if you can provide a fiddle since I've no idea of the "types" you are talking about.

**Comment by justmeandtaken** [comment]
@jails I will try to create a fiddle from  now on. Anyway. How do you handle the edge cases??

Example:

-  'checkOn' in checkboxes fails on Android 4.1 and lower, 
-  IE 11 and lower. An input loses its value after becoming a radio
-  IE11 and lower have problems with selectedIndex
and other known issues

**Comment by jails** [comment]
Like every body do, one by one ;-)
Btw I've no idea what is the `checkOn` attribute.

**Comment by justmeandtaken** [comment]
@jails That was my mistake. I took examples from my old code regarding this issues.

```javascript
// Android 4.4 and lower
var input = DOCUMENT.createElement( "input" );
     input.type = "checkbox";
 checkOn = input.value !== ""; // Default value for a checkbox should be "on"

// And then:

if ( node.type === "checkbox" && !checkOn ) return node.getAttribute( "value" ) === null ? "on" : node.value;


 // Support: IE<=11+
 // An input loses its value after becoming a radio
    input.type = "radio";
    input.value = "t";
    radioValue = input.value === "t";

// And then:

if ( value === "radio" ) {
            var val = node.value;

            node.setAttribute( "type", val );
            
            if ( value ) node.value = val;

        } else {
            node.type = value;
        }

```
