### ISSUE TITLE
Wrong info in readme

### ISSUE THREAD

**Issue by justmeandtaken** [crysalead-js/dom-layer#13]
@jails Take a look here: https://github.com/crysalead-js/dom-layer#the-tags-options-parameter

You are mention **style** as a stand-alone Tag option, but in real life **style** are part of the attr Tag option.

And **attrsNS** are not mentioned.

**Comment by jails** [comment]
Good catch `attrsNS` is missing I'll add it, however looks like `style` is correctly defined inside the `attrs` property in the definition.

**Comment by jails** [comment]
Fixed in https://github.com/crysalead-js/dom-layer/commit/5db047e8926bfba2352a97967775e87cb5226016
