### ISSUE TITLE
QSA got a lot of errors

### ISSUE THREAD

**Issue by justmeandtaken** [crysalead-js/dom-layer#15]
querySelector[All] got a lot of errors, and also with child nodes in IE9.

**Comment by jails** [comment]
What kind of errors ? Afaik querySelector is IE9 compatible.

**Comment by justmeandtaken** [comment]
You can go 7 years back in time and start with this. 

http://ejohn.org/blog/thoughts-on-queryselectorall/

There are many more. Take a look at the dojo toolkit and their workaround

**Comment by jails** [comment]
Well I don't think it's related to the dom-layer. If people use selectors unsupported by IE9 as mount point, they'll need to include the polyfills needed to make it work on the legacy browser they want to support imo.
