### ISSUE TITLE
issues with mounting

### ISSUE THREAD

**Issue by justmeandtaken** [crysalead-js/dom-layer#18]
If you have multiple div-tags with the same class and you try to mount on the classes, this code will be affected: https://github.com/crysalead-js/dom-layer/blob/master/tree/tree.js#L26-L29

I'm right?

Anyway. Nothing will be visible in the browser and / or seems to get mounted. Also seems to be an issue then with the mounting index.

**Comment by jails** [comment]
As I said in https://github.com/crysalead-js/dom-layer/issues/17, I'll probably remove this anytime soon since multiple "mounting" should be managed at a higher level. And if a selector returns more than one element, I'll just throw an error instead.

**Comment by jails** [comment]
I finally removed it for now until I've another idea https://github.com/crysalead-js/dom-layer/commit/7918a23b4eab6fdfe17f7433ff921b94cd54b6ff
