### ISSUE TITLE
mount / unmount should add / remove events

### ISSUE THREAD

**Issue by justmeandtaken** [crysalead-js/dom-layer#23]
When you unmount a tree, it should also unmount / remove all events attached to it.
And what about a unmountAll() method to remove all mounted trees at once, included the events?

And when you mount a tree, it should automaticly bind the events to it? Shouldn't that be easier to do event delegation?

**Comment by justmeandtaken** [comment]
And also when you remove a virtual node, should make sure the events attached to it is gone.

For patching, make sure events get copied / patched.

**Comment by jails** [comment]
With delegated events, events are not attached to DOM element or mounted tree but only `document.body`.

So before starting playing with the vdom you need to initialize the event manager with default events. And if you need to clear things up, just call `unbind()` on the event manager.
```js
var domLayer = require("dom-layer");
var eventManager = domLayer.events.init();

// play with the vdom

eventManager.unbind() // In case of you play with "some dynamic vdom"
```
