### ISSUE TITLE
custom element

### ISSUE THREAD

**Issue by rickardjanson** [crysalead-js/dom-layer#26]
I saw REACT discussing this, and also Virtual DOM have discussed and have a open PR. 
https://github.com/Matt-Esch/virtual-dom/pull/207/files

Is this something to be implemented?

**Comment by jails** [comment]
Yeah sure, it's not something I'm using but why not.

**Comment by jails** [comment]
Implemented in https://github.com/crysalead-js/dom-layer/commit/9817c4c362ea0a25e36f1378972274e75ce5564e and https://github.com/crysalead-js/dom-layer/commit/4c492dfb3399aabed2ca3d664cf9f2950dcddd8e for the related spec.

**Comment by rickardjanson** [comment]
Ok. I saw you have a lot of new changes. I will bug test later. Just now no electricity or water after earthquake. Bad signals on mobile too.

**Comment by jails** [comment]
earthquake ? wow hope everything will be back as normal soon ;-)

**Comment by rickardjanson** [comment]
5.8 on ritchers. Not so strong this time. I'm in Asia during some work. Tonight or tomorrow everything is back I hope. No more battery

**Comment by rickardjanson** [comment]
@jails Not sure if I can bug test anything more today. We got a new earthquake now 1 hour ago. http://www.google.org/publicalerts/alert?aid=1b0b1d3afcf00bec&hl=en&gl=PH&source=web

I still have electricity, but we will see.
