### ISSUE TITLE
Missing `capture` and `multiple` attribute in `<input type="file" />`

### ISSUE THREAD

**Issue by rickardjanson** [crysalead-js/dom-layer#29]
Same for domLayer as for React. See this issue here: https://github.com/facebook/react/issues/3948

**Note!!** If you try with `.toHtml` your output would be  `<div accept="image/*"></div>`

As you see both `capture` and `multiple` are missing.

If you are not using `.toHtml`, you still get the same issues.

**Comment by jails** [comment]
I don't see any issue with file input https://github.com/crysalead-js/dom-layer/commit/066a9c7ac7ed937bd5da6fa956eebf053bc3cc9d

**Comment by rickardjanson** [comment]
I see it now. I had a older version of your code running, plus I forget to add the type attr.
