### ISSUE TITLE
'key' in Text() does nothing

### ISSUE THREAD

**Issue by justmeandtaken** [crysalead-js/dom-layer#3]
Hi, @jails  I'm still studying your code here because I like your work! Anyway. The Text() function, you got a second argument there - **key**. This **key** are never used. What is the plans for it?

**Comment by jails** [comment]
Indeed it's a mistake, Having a key property for `Text` node doesn't make sense, I removed it.

**Comment by justmeandtaken** [comment]
@jails Ok. Btw. There are also other places where you have attributes that have no real purpose. 

Here is another example: https://github.com/crysalead-js/dom-layer/blob/master/dist/dom-layer.js#L82

Couple of others:

https://github.com/crysalead-js/dom-layer/blob/master/dist/dom-layer.js#L5
https://github.com/crysalead-js/dom-layer/blob/master/dist/dom-layer.js#L50

This *node* have no real world purpose has it?

**Comment by jails** [comment]
Good catch :+1:, I did a couple of refactoring and I forgot to remove them.
