### ISSUE TITLE
support for rdfa attributes

### ISSUE THREAD

**Issue by rickardjanson** [crysalead-js/dom-layer#30]
should you add support for rdfa attributes such as `resource`, `about`, `property`? http://www.w3.org/TR/rdfa-core/#h-s_syntax

**Comment by jails** [comment]
Sorry, I've no idea what is that. How is that different from classic attributes ?

**Comment by rickardjanson** [comment]
`Resource Description Framework`.   You can get ideas here I guess http://www.ibm.com/developerworks/library/wa-rdfalite/

**Comment by rickardjanson** [comment]
You can also get ideas here http://stackoverflow.com/questions/16873611/in-rdfa-difference-between-property-rel-and-resource-about

**Comment by jails** [comment]
Looks like it's just attributes, what part requires some tweaks ?

**Comment by rickardjanson** [comment]
This is not normal attributes, and uses namespace. Have a look here http://www.w3.org/TR/html-rdfa/#preserving-namespaces-via-coercion-to-infoset

**Comment by rickardjanson** [comment]
If the RDFa @property attribute is present on the link element, the @rel attribute is not required.
If the RDFa @resource attribute is present on the link element, the @href attribute is not required.
If the RDFa @property attribute is present on the meta element, neither the @name, @http-equiv, nor @charset attributes are required and the @content attribute must be specified.

**Comment by jails** [comment]
Since this constraints should be the same when working on the DOM, it's imo up to the developper to respect them.
