### ISSUE TITLE
style stringify

### ISSUE THREAD

**Issue by rickardjanson** [crysalead-js/dom-layer#32]
Look at how REACT does this: https://github.com/facebook/react/blob/0.13-stable/src/browser/ui/dom/CSSPropertyOperations.js#L107-L137

And also have a closer look at their dangerousStyleValues function

**Comment by jails** [comment]
The dom-layer assumes you are providing some valid CSS. If people wan't to implement some "CSS validation checker feature" I think it's better to add it a higher level of abstraction.
