### ISSUE TITLE
improve patching 

### ISSUE THREAD

**Issue by rickardjanson** [crysalead-js/dom-layer#37]
Read this post:https://www.bountysource.com/issues/10834294-smarter-redrawing-diff-a-tree-of-values-rather-than-a-tree-of-virtual-dom

**Comment by jails** [comment]
The dom-layer only provides necessary building blocks (i.e. `mount()`/`unmount()`/`update()`) to split things in subtrees. It's up to a higher level of abstration to attach to each components a dedicated subtree and only perform updates for components which are actually "dirty".
