### ISSUE TITLE
suggestions 

### ISSUE THREAD

**Issue by rickardjanson** [crysalead-js/dom-layer#44]
I was just thinking. What if you move all hooks to the Tag prototype? Then you can get options like attr, prop, add class etc directly. As you can use in a higher level.

See js blocks and it's virtual dom.

https://github.com/astoilkov/jsblocks/blob/master/src/query/VirtualElement.js

**Comment by jails** [comment]
I don't think it's a good solution. All virtual nodes should share a common interface imo. If you add methods to the `Tag` virtual node, you will require to type check your node to know wha
