### ISSUE TITLE
no updated callback??

### ISSUE THREAD

**Issue by rickardjanson** [crysalead-js/dom-layer#46]
I took a look at your new changes, and as far as I can see, there is no `updated()` callback?
Quick search in the source code gave no match. Is this a bug?

**Comment by rickardjanson** [comment]
No bug. You haven't published a new release yet!!.

**Comment by jails** [comment]
Ah yeah needed to remove an unecessary dependency first.

**Comment by rickardjanson** [comment]
But are this callback working all the time for you? I tried the update spec and got a different result... if you have A and patch it with B, the new node will be C with changes from A? Because I got sometimes this:  

A B B A

and not

A B A B

As in the specs. I will see if I can create I js fiddle later on.
