### ISSUE TITLE
tspan

### ISSUE THREAD

**Issue by rickardjanson** [crysalead-js/dom-layer#48]
Are tspans supported and working? 

Seems like there could be in issue if some SVG elements get created inside a <div> tag.
They will be initialized in the wrong namespace (and will not display).
Example if you getting the parent namespace...

Also study this: https://github.com/facebook/react/issues/3972

**Comment by jails** [comment]
I did this library because I don't share the React coding philosophy. So I'm not really interested to waste my time on it.
So better to open here issues which actually exists in dom-layer https://jsfiddle.net/ectoqbds/
