### ISSUE TITLE
selectedIndex should be skipped in htmlify

### ISSUE THREAD

**Issue by rickardjanson** [crysalead-js/dom-layer#49]
`selectedIndex` are an property and as you stated before, it should be set with props. Shouldn't this then be avoided in `.toHTML()`?

And if the attribute value is true, correct html should be to set the value to  `''` ? 

And simply ignore if it's an false value?

**Comment by rickardjanson** [comment]
And if you are htmlify a boolean value, this will never be correct, or? Example `checked`. It`s set as an property, but if an boolean and htmlify, it should become  `<checked> <checked>`. 
In your solution it will one be ` true / false `.

**Comment by jails** [comment]
`selectedIndex` is a property so there's no need to skip anything since the whole `props` is ignored from `.toHTML()`.
And the dom-layer is not a property/attribute checker. You need to pass correct values to make it work. So for checked it's `attrs: {"checked": "checked"}`.
