### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by ghost** [crysalead-js/dom-layer#5]
@jails  I noticed there are some performance things you can fix to gain better performance. After some experimenting, I actually managed to get domLayer to be 2 - 4% faster then CitoJS. I did so because I refactored some of your iteration loops etc.

Anyway. What I wonder about is inside the Tag.js function. You are iterating through applyAttrsNS even if there are no data. It will only produce empty object and do nothing. Same for applyProps() and applyAttrs().

This is both for the create() function and the patch() function inside the Tag() prototype.

Any reason for this?

And you are also doing for me a strange thing. You are passing in a empty object in the same mentioned functions as the previous value. Then inside each of this setters you are again checking if previous existing and if not an empty object.

**Comment by jails** [comment]
Afaik applying attributes just bail out when they are undefined (https://github.com/crysalead-js/dom-layer/blob/master/node/setter/apply-attrs.js#L5).

For this: https://github.com/crysalead-js/dom-layer/blob/master/node/tag.js#L45, the other option was to create some dedicated funtions to set initial attributes/properties. But it's equivalent to consider that the node has no attributes, so each present attributes in `this.attrs` will be setted. No need to have some dedicated functions just for that.

**Comment by jails** [comment]
I guess I won't have any more performance feeback from a removed user, so I'm closing this.

**Comment by rickardjanson** [comment]
@jails No need to close this. I'm still here. This was my first time using Github and someone had taken my username etc. Long story made short, I'm back as me. 

I still like your code and want to help you out.

Sorry for what happen!
