### ISSUE TITLE
Input value on IE 

### ISSUE THREAD

**Issue by marcorra** [crysalead-js/dom-layer#61]
Have a look here: https://github.com/Matt-Esch/virtual-dom/issues/287

Same issue for dom-layer, even in MS Edge.

**Comment by jails** [comment]
I don't have IE so I created an [ie-fix](https://github.com/crysalead-js/dom-layer/tree/ie-fix/dist) banch. Would you mind testing it for me ?

**Comment by marcorra** [comment]
@jails Confirmed not working!! After I started to study your code. There is no patch spec for props so didn't test that. However, look at your code? There is an unused value attribute there?
I can get it to work in ie if I change the code to this, but then you attribute spec fails for me. BANG!

```
var value = element.getAttribute('value');
			    element.setAttribute(attrs[name], value);
                element[name] = value;
```
I checked in all IE now, and IE10 give other issues to with your code. I need to double check

**Comment by marcorra** [comment]
Other IE issues was only in IE9 and IE10. When patching boolean attributes... Expecting "" to be a true value. and for patching SVG it want "" to be a null, same for unsetting a xml namespace. It want "" to be null.

**Comment by jails** [comment]
Ah yeah indeed, not totally awake... just  fixed that. Otherwise according to [global stats](http://gs.statcounter.com/#browser_version-ww-monthly-201406-201506) IE<11 are less used than IE8. And since IE8 is way to old for being supported, I don't think supporting all IE<11 worth the effort.

**Comment by marcorra** [comment]
issue are if `value` are set before `type` in IE, so you need to reverse the order to `type` first and `value` last

**Comment by jails** [comment]
In IE updating the "type" attribute reset the value. So to become generic, I'm just saving the element value before updating its "type" and then applying the previous "value" on it to restore it.
It should work.

**Comment by jails** [comment]
During patching you are not always patching both `type` and `value` at the same time. Indeed patching is only done when an attribute is modified.
So if at some point you only change the `type` attribute value, you'll need to take care of the `value` attribute which will be reseted on IE

**Comment by marcorra** [comment]
I understand you, but IE are not agree :) Your spec works, but in MS Edge there is an issue.

**Comment by jails** [comment]
can you gist me the example you are using which doesn't work on MS Edge ?

**Comment by marcorra** [comment]
Just see my updated comment.

**Comment by jails** [comment]
I asked a friend to test this fiddle on IE11 https://jsfiddle.net/x8kg328c/ and it worked.
You are probably not using the last dist file of the ie-fix branch.

**Comment by marcorra** [comment]
Jsfiddle works. So I guess this is solved.

**Comment by jails** [comment]
Yup, I'll merge that.

**Comment by marcorra** [comment]
Another issue raises. When you have a separate hook for type, this would give another IE issues I figured out when you getting the value with `getAttribute`. Or I'm wrong

 See jquery code here and see if we see the same:

```
var val = jQuery.find.attr( elem, "value" );
				return val != null ?
					val :
					// Support: IE10-11+
					// option.text throws exceptions (#14686, #14858)
					jQuery.trim( jQuery.text( elem ) );
```

**Comment by jails** [comment]
It's more a bug related to `<option>` tags and the jquery `val()` abstraction. I don't see any issue here for dom-layer

**Comment by marcorra** [comment]
Ok. I was just reading - not only in jquery - that the issue was `getAttribute` sometimes can return null for `type`. as your hooks is `type`.
