### ISSUE TITLE
textarea, listing and pre server side issue

### ISSUE THREAD

**Issue by rickardjanson** [crysalead-js/dom-layer#67]
I noticed that textarea are not rendered correctly either? It's ignored, but shouldn't the value of textarea become it context? ``` <textarea value="jails"></textarea>``` should become``` <textarea>jails</textarea>```

Same also for `listing` and `pre`

**Comment by jails** [comment]
Indeed can be problematic, fixed in the last master.

**Comment by jails** [comment]
In dom-layer the `"value"` attribute for `<select>` & `<textearea>` has been "introduced" to be able to simplify value handling of inputs.

But for `<listing>` or `<pre>`, `"value"` is not a valid attribute. You should set the content by setting the children correclty (like with `<p>`, `<span>` or `<div>`)
