### ISSUE TITLE
Replace browserify with rollupjs 

### ISSUE THREAD

**Issue by kolya-ay** [crysalead-js/dom-layer#68]
It seems that [it's better](http://rollupjs.org/) choice for libraries at least. It generates almost no boilerplate

**Comment by jails** [comment]
Looks interesting!
Anyhow the provided dist file is only provided to make it easier to use this library in some online tool like jsFiddle.
People can still use `rollupjs` or the tool you want to bunde up all of your dependencies through `node`.

**Comment by kolya-ay** [comment]
I think it still makes sense as `rollupjs` not only provides the solution but also proposes [a standard](https://github.com/rollup/rollup/wiki/jsnext:main) for having best of two worlds

**Comment by jails** [comment]
dom-layer doesn't define the "main" entry as "dist/dom-layer.js" in its package.json. `index.js` is still the entry point so the generated build will depends on your tooling. So if you are using rollupjs in your project, dom-layer will be build using rollupjs. `dist/dom-layer.js` won't be included as is. `dist/dom-layer.js` is only present to make some JSFiddle without to much headach.
