### ISSUE TITLE
Patching may render nodes with no parent

### ISSUE THREAD

**Issue by brandonpayton** [crysalead-js/dom-layer#71]
[This](https://github.com/crysalead-js/dom-layer/blob/4cc90c5197d42155a462eed31145d4a397d4510b/src/tree/patch.js#L57) and [this](https://github.com/crysalead-js/dom-layer/blob/4cc90c5197d42155a462eed31145d4a397d4510b/src/tree/patch.js#L71) from src/tree/patch.js combined with [Tag#render](https://github.com/crysalead-js/dom-layer/blob/4cc90c5197d42155a462eed31145d4a397d4510b/src/node/tag.js#L70), which now takes two arguments, mean that some nodes inserted by patch are created without a node `parent`.

I updated the patch text and node insertion specs to reproduce by asserting that immediate children of the `from` and `to` trees have a `parent`. Only the `to` trees fail the assertion. The repro commit is [here](https://github.com/brandonpayton/dom-layer/commit/a6827421f922cfeab97d8136e3f41b194c8515b8).

**Comment by jails** [comment]
Good catch, open it as PR so I can merge it.

**Comment by jails** [comment]
I'm closing this in flavor of the PR.
