### ISSUE TITLE
Tag's created hook should always run after insertion in the DOM

### ISSUE THREAD

**Issue by brandonpayton** [crysalead-js/dom-layer#72]
Tag's `created` hook is called inconsistently relative to when its element is inserted in the DOM.
- When a container is provided to `Tag#render`, the `created` hook is called after the node's element is inserted in the DOM, but when `Tag#render` appends itself to a document fragment, `created` is called before the node is added to the DOM document by `tree/patch`.
- This matters because `created` hooks may need to do things like take layout measurements which require being part of the document flow.
- There may be a place for both pre and post insertion hooks, but I believe at least a post insertion hook is necessary for the reason above.

I don't have a strong idea how this should be fixed in the current implementation. Since you likely want to do child insertions before the parent is added to the DOM, I believe you will have to walk the tree to render, insert the parent in the DOM, and then walk the tree again to fire `created` hooks.

**Comment by jails** [comment]
Hmm I'll need to think about it a bit.

**Comment by jails** [comment]
Fixed in https://github.com/crysalead-js/dom-layer/commit/88ff26d5bc82730c495c96dcf679261263cf54ad
