### ISSUE TITLE
sometimes 'this.parent' don't exist

### ISSUE THREAD

**Issue by justmeandtaken** [crysalead-js/dom-layer#9]
@jails I tried your latest changes, but got some errors. In the renders.spec as one example it seems that sometimes the **this.parent** are not existing. See: **renders text node inside block node**.

Actually I got over 40 errors!!

**Comment by justmeandtaken** [comment]
@jails Try this, and have a look into the console:

```javascript
  var node = h({ tagName: "span" }, ["hello"]);
         node = node.render();
```

For me I only see this:  **TypeError: this.parent is undefined**

**Comment by jails** [comment]
Yup I forgot to run `npm run dist` so the build files was broken.
